Repository spring-cloud/spring-cloud-netflix, pull requests merged in 2018-12, with the labels that each got.

#3297 Submit PR #3276 against the 2.0.x branch
  spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/hystrix/security/HystrixSecurityAutoConfiguration.java
  spring-cloud-netflix-core/src/test/java/org/springframework/cloud/netflix/hystrix/security/HystrixSecurityAutoConfigurationTest.java
Labels: waiting for feedback

#3306 Added option to not decode URL. PR to 2.0.x. Fixes gh-2178
  docs/src/main/asciidoc/spring-cloud-netflix.adoc
  spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/filters/ProxyRequestHelper.java
  spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/filters/ZuulProperties.java
  spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/filters/pre/PreDecorationFilter.java
  spring-cloud-netflix-zuul/src/test/java/org/springframework/cloud/netflix/zuul/filters/pre/PreDecorationFilterTests.java
Labels: waiting-for-triage

#3312 Fix typo in documentation
  docs/src/main/asciidoc/spring-cloud-netflix.adoc
Labels: documentation

#3317 Inner map metrics with same name are being overwritten on actuator me…
  spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/hystrix/HystrixCircuitBreakerConfiguration.java
  spring-cloud-netflix-core/src/test/java/org/springframework/cloud/netflix/hystrix/HystrixOnlyTests.java
Labels: bug

#3323 Fix compatible issue with spring boot 2.0
  spring-cloud-netflix-sidecar/src/main/java/org/springframework/cloud/netflix/sidecar/SidecarConfiguration.java
Labels: waiting-for-triage
