Repository spring-cloud/spring-cloud-netflix, pull requests merged in 2018-05, with the labels that each got.

#2880 Use Type String Instead Of Class In Conditionals
  spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/feign/encoding/FeignAcceptGzipEncodingAutoConfiguration.java
  spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/feign/encoding/FeignContentGzipEncodingAutoConfiguration.java
Labels: in progress

#2916 Fix typo in docs
  docs/src/main/asciidoc/spring-cloud-netflix.adoc
Labels: documentation

#2950 [Turbine Stream] Fixes JSON format errors with Hystrix Dashboard.
  spring-cloud-netflix-turbine-stream/src/main/java/org/springframework/cloud/netflix/turbine/stream/TurbineController.java
Labels: bug, in progress
