Repository spring-cloud/spring-cloud-netflix, pull requests merged in 2018-11, with the labels that each got.

#3257 Upgrade eureka version
  spring-cloud-netflix-dependencies/pom.xml
  spring-cloud-netflix-eureka-server/src/main/java/org/springframework/cloud/netflix/eureka/server/EurekaServerAutoConfiguration.java
  spring-cloud-netflix-eureka-server/src/main/java/org/springframework/cloud/netflix/eureka/server/EurekaServerConfigBean.java
  spring-cloud-netflix-eureka-server/src/main/java/org/springframework/cloud/netflix/eureka/server/InstanceRegistry.java
  spring-cloud-netflix-eureka-server/src/main/java/org/springframework/cloud/netflix/eureka/server/InstanceRegistryProperties.java
Labels: enhancement

#3271 upgrade ribbon version
  spring-cloud-netflix-dependencies/pom.xml
Labels: enhancement

#3278 Add support for CORS requests
  docs/src/main/asciidoc/spring-cloud-netflix.adoc
  spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/ZuulServerAutoConfiguration.java
  spring-cloud-netflix-zuul/src/test/java/org/springframework/cloud/netflix/zuul/ZuulProxyApplicationTests.java
Labels: waiting for feedback

#3288 Upgrade Hystrix to 1.5.18
  spring-cloud-netflix-dependencies/pom.xml
Labels: task

#3291 Document workaround for conflicting Thymeleaf dependency (spring-clou…
  docs/src/main/asciidoc/spring-cloud-netflix.adoc
Labels: feedback-provided

#3215 Added the instance id to the `EurekaServiceInstance`, `EurekaRegistration` and `RibbonLoadBalancerClient`
  spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/EurekaDiscoveryClient.java
  spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/serviceregistry/EurekaRegistration.java
  spring-cloud-netflix-eureka-client/src/test/java/org/springframework/cloud/netflix/eureka/EurekaInstanceConfigBeanTests.java
  spring-cloud-netflix-eureka-client/src/test/java/org/springframework/cloud/netflix/eureka/serviceregistry/EurekaServiceRegistryTests.java
  spring-cloud-netflix-ribbon/src/main/java/org/springframework/cloud/netflix/ribbon/RibbonLoadBalancerClient.java
  spring-cloud-netflix-ribbon/src/test/java/org/springframework/cloud/netflix/ribbon/RibbonLoadBalancerClientTests.java
Labels: enhancement
