Repository spring-cloud/spring-cloud-netflix, pull requests merged in 2018-10, with the labels that each got.

#3221 Only copy the requestentity in zuul if the request is retryable
  spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/route/RibbonCommandContext.java
Labels: in progress

#3212 Use the appname and id from in mem instanceInfo object instead of raw config
  spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/serviceregistry/EurekaServiceRegistry.java
  spring-cloud-netflix-eureka-client/src/test/java/org/springframework/cloud/netflix/eureka/serviceregistry/EurekaServiceRegistryTests.java
Labels: bug

#3224 Sidecar: add accept-all-ssl-certificates property in order to be able to use https health checks with self-signed certificates
  docs/src/main/asciidoc/spring-cloud-netflix.adoc
  spring-cloud-netflix-sidecar/src/main/java/org/springframework/cloud/netflix/sidecar/LocalApplicationHealthIndicator.java
  spring-cloud-netflix-sidecar/src/main/java/org/springframework/cloud/netflix/sidecar/SidecarConfiguration.java
  spring-cloud-netflix-sidecar/src/main/java/org/springframework/cloud/netflix/sidecar/SidecarProperties.java
  spring-cloud-netflix-sidecar/src/test/java/org/springframework/cloud/netflix/sidecar/SidecarApplicationTests.java
  spring-cloud-netflix-sidecar/src/test/resources/application.yml
Labels: enhancement

#3240 Do Not Use AIM Proxy In EurekaClient
  spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/EurekaClientAutoConfiguration.java
Labels: in progress

#3241 [Sidecar] Check ssl certificate property inside the bean creation method
  spring-cloud-netflix-sidecar/src/main/java/org/springframework/cloud/netflix/sidecar/SidecarConfiguration.java
Labels: in progress

#3242 Deprecate spring-cloud-netflix-core and move functionality over to spring-cloud-netflix-hystrix
  docs/src/main/asciidoc/spring-cloud-netflix.adoc
  pom.xml
  spring-cloud-netflix-core/pom.xml
  spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/core/CoreAutoConfiguration.java
  spring-cloud-netflix-core/src/main/resources/META-INF/spring.factories
  spring-cloud-netflix-dependencies/pom.xml
  spring-cloud-netflix-eureka-client/pom.xml
  spring-cloud-netflix-eureka-server/pom.xml
  spring-cloud-netflix-hystrix-dashboard/pom.xml
  spring-cloud-netflix-hystrix-stream/pom.xml
  spring-cloud-netflix-hystrix/pom.xml
  spring-cloud-netflix-hystrix/src/main/java/org/springframework/cloud/netflix/hystrix/EnableHystrix.java
  spring-cloud-netflix-hystrix/src/main/java/org/springframework/cloud/netflix/hystrix/HystrixAutoConfiguration.java
  spring-cloud-netflix-hystrix/src/main/java/org/springframework/cloud/netflix/hystrix/HystrixCircuitBreakerConfiguration.java
  spring-cloud-netflix-hystrix/src/main/java/org/springframework/cloud/netflix/hystrix/HystrixCommands.java
  spring-cloud-netflix-hystrix/src/main/java/org/springframework/cloud/netflix/hystrix/HystrixConstants.java
  spring-cloud-netflix-hystrix/src/main/java/org/springframework/cloud/netflix/hystrix/HystrixHealthIndicator.java
  spring-cloud-netflix-hystrix/src/main/java/org/springframework/cloud/netflix/hystrix/HystrixMetricsProperties.java
  spring-cloud-netflix-hystrix/src/main/java/org/springframework/cloud/netflix/hystrix/HystrixProperties.java
  spring-cloud-netflix-hystrix/src/main/java/org/springframework/cloud/netflix/hystrix/HystrixStreamEndpoint.java
  spring-cloud-netflix-hystrix/src/main/java/org/springframework/cloud/netflix/hystrix/HystrixWebfluxEndpoint.java
  spring-cloud-netflix-hystrix/src/main/java/org/springframework/cloud/netflix/hystrix/security/HystrixSecurityAutoConfiguration.java
  spring-cloud-netflix-hystrix/src/main/java/org/springframework/cloud/netflix/hystrix/security/SecurityContextConcurrencyStrategy.java
  spring-cloud-netflix-hystrix/src/main/resources/META-INF/additional-spring-configuration-metadata.json
  spring-cloud-netflix-hystrix/src/main/resources/META-INF/spring.factories
  spring-cloud-netflix-hystrix/src/test/java/org/springframework/cloud/netflix/AdhocTestSuite.java
  spring-cloud-netflix-hystrix/src/test/java/org/springframework/cloud/netflix/hystrix/HystrixAutoConfigurationTests.java
  spring-cloud-netflix-hystrix/src/test/java/org/springframework/cloud/netflix/hystrix/HystrixCommandsTests.java
  spring-cloud-netflix-hystrix/src/test/java/org/springframework/cloud/netflix/hystrix/HystrixConfigurationTests.java
  spring-cloud-netflix-hystrix/src/test/java/org/springframework/cloud/netflix/hystrix/HystrixOnlyTests.java
  spring-cloud-netflix-hystrix/src/test/java/org/springframework/cloud/netflix/hystrix/HystrixStreamEndpointTests.java
  spring-cloud-netflix-hystrix/src/test/java/org/springframework/cloud/netflix/hystrix/HystrixWebfluxEndpointTests.java
  spring-cloud-netflix-hystrix/src/test/java/org/springframework/cloud/netflix/hystrix/security/HystrixSecurityApplication.java
  spring-cloud-netflix-hystrix/src/test/java/org/springframework/cloud/netflix/hystrix/security/HystrixSecurityNoFeignTests.java
  spring-cloud-netflix-hystrix/src/test/java/org/springframework/cloud/netflix/hystrix/security/app/CustomConcurrenyStrategy.java
  spring-cloud-netflix-hystrix/src/test/java/org/springframework/cloud/netflix/hystrix/security/app/UsernameController.java
  spring-cloud-netflix-hystrix/src/test/java/org/springframework/cloud/netflix/resttemplate/RestTemplateRetryTests.java
  spring-cloud-netflix-hystrix/src/test/java/org/springframework/cloud/netflix/ribbon/apache/HttpClientStatusCodeExceptionTest.java
  spring-cloud-netflix-hystrix/src/test/java/org/springframework/cloud/netflix/ribbon/okhttp/OkHttpStatusCodeExceptionTest.java
  spring-cloud-netflix-hystrix/src/test/java/org/springframework/cloud/netflix/test/NoSecurityConfiguration.java
  spring-cloud-netflix-hystrix/src/test/java/org/springframework/cloud/netflix/test/TestAutoConfiguration.java
  spring-cloud-netflix-hystrix/src/test/resources/META-INF/spring.factories
  spring-cloud-netflix-hystrix/src/test/resources/application.yml
  spring-cloud-netflix-hystrix/src/test/resources/archaius_db_store.sql
  spring-cloud-netflix-hystrix/src/test/resources/config.properties.bak
  spring-cloud-netflix-hystrix/src/test/resources/static/index.html
  spring-cloud-netflix-sidecar/pom.xml
  spring-cloud-netflix-turbine-stream/pom.xml
  spring-cloud-netflix-turbine/pom.xml
  spring-cloud-netflix-zuul/pom.xml
  spring-cloud-starter-netflix/spring-cloud-starter-netflix-eureka-client/pom.xml
  spring-cloud-starter-netflix/spring-cloud-starter-netflix-hystrix/pom.xml
Labels: in progress
