Repository spring-cloud/spring-cloud-netflix, pull requests merged in 2019-05, with the labels that each got.

#3530 Cleanup ThreadLocal in SendResponseFilter
  spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/zuul/filters/post/SendResponseFilter.java
Labels: in progress

#3533 adds caution about property name case-sensitivity
  docs/src/main/asciidoc/spring-cloud-netflix.adoc
Labels: waiting-for-triage

#3543 fix typo
  spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/http/RestTemplateTransportClientFactory.java
Labels: waiting for feedback
