Repository spring-cloud/spring-cloud-netflix, pull requests merged in 2019-02, with the labels that each got.

#3356 Issue-3305. Way to set securePortEnabled option for sidecar
  docs/src/main/asciidoc/spring-cloud-netflix.adoc
  spring-cloud-netflix-sidecar/src/main/java/org/springframework/cloud/netflix/sidecar/SidecarConfiguration.java
  spring-cloud-netflix-sidecar/src/main/java/org/springframework/cloud/netflix/sidecar/SidecarProperties.java
  spring-cloud-netflix-sidecar/src/test/java/org/springframework/cloud/netflix/sidecar/SidecarApplicationTests.java
Labels: enhancement, waiting for feedback

#3374 Fix defect of hystrix stream queue configuration
  spring-cloud-netflix-hystrix-stream/src/main/java/org/springframework/cloud/netflix/hystrix/stream/HystrixStreamTask.java
Labels: enhancement

#3382 Use server.servlet.context-path instead of server.context-path for prefix to health check and info URLs
  spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/EurekaClientAutoConfiguration.java
Labels: bug

#3386 Set `failsOnError` to `true`.
  pom.xml
Labels: in progress

#3381 fix SidecarController's broken link.
  spring-cloud-netflix-sidecar/src/main/java/org/springframework/cloud/netflix/sidecar/SidecarController.java
Labels: documentation

#3390 Make spring.cloud.discovery.enabled work as eureka.client.enabled
  docs/src/main/asciidoc/spring-cloud-netflix.adoc
  spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/EurekaClientAutoConfiguration.java
  spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/EurekaDiscoveryClientConfiguration.java
  spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/ribbon/eureka/ConditionalOnRibbonAndEurekaEnabled.java
  spring-cloud-netflix-eureka-client/src/test/java/org/springframework/cloud/netflix/eureka/EurekaClientAutoConfigurationTests.java
Labels: for team discussion, in progress

#3398 Fix encoding when retryring requests
  spring-cloud-netflix-ribbon/src/main/java/org/springframework/cloud/netflix/ribbon/apache/RetryableRibbonLoadBalancingHttpClient.java
  spring-cloud-netflix-ribbon/src/test/java/org/springframework/cloud/netflix/ribbon/apache/RibbonLoadBalancingHttpClientTests.java
Labels: in progress
