Repository spring-cloud/spring-cloud-netflix, pull requests merged in 2019-09, with the labels that each got.

#3407 Re-create connection manager on "zuul.host.*" property change
  spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/filters/route/SimpleHostRoutingFilter.java
  spring-cloud-netflix-zuul/src/test/java/org/springframework/cloud/netflix/zuul/filters/route/SimpleHostRoutingFilterTests.java
Labels: enhancement

#3647 Add Spring Cloud LoadBalancer starter to Eureka starters.
  docs/src/main/asciidoc/spring-cloud-netflix.adoc
  spring-cloud-starter-netflix/spring-cloud-starter-netflix-eureka-client/pom.xml
  spring-cloud-starter-netflix/spring-cloud-starter-netflix-eureka-server/pom.xml
Labels: waiting-for-triage

#3650 Update docs.
  docs/README.adoc
  docs/pom.xml
  docs/src/main/asciidoc/README.adoc
  docs/src/main/asciidoc/_attributes.adoc
  docs/src/main/asciidoc/_configprops.adoc
  docs/src/main/asciidoc/appendix.adoc
  docs/src/main/asciidoc/intro.adoc
  docs/src/main/asciidoc/maintenance-mode.adoc
  docs/src/main/asciidoc/sagan-boot.adoc
  docs/src/main/asciidoc/sagan-index.adoc
  docs/src/main/asciidoc/spring-cloud-circuitbreaker-hystrix.adoc
  docs/src/main/asciidoc/spring-cloud-netflix.adoc
Labels: waiting-for-triage

#3609 ConditionalOnMissingBean on formBodyWrapperFilter, debugFilter and servlet3...
  spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/ZuulServerAutoConfiguration.java
Labels: enhancement

#3657 Fix RestTemplateEurekaHttpClient status update endpoint
  spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/EurekaClientAutoConfiguration.java
  spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/http/RestTemplateEurekaHttpClient.java
Labels: in progress

#3665 Gh 3409 turbine stream test
  spring-cloud-netflix-turbine-stream/pom.xml
  spring-cloud-netflix-turbine-stream/src/test/java/org/springframework/cloud/netflix/turbine/stream/TurbineStreamTests.java
Labels: waiting-for-triage

#3660 Optimize code of eureka
  spring-cloud-netflix-eureka-client/src/test/java/org/springframework/cloud/netflix/eureka/healthcheck/EurekaHealthCheckTests.java
  spring-cloud-netflix-eureka-client/src/test/java/org/springframework/cloud/netflix/eureka/http/EurekaServerMockApplication.java
  spring-cloud-netflix-eureka-client/src/test/java/org/springframework/cloud/netflix/eureka/sample/EurekaSampleApplication.java
  spring-cloud-netflix-eureka-client/src/test/java/org/springframework/cloud/netflix/ribbon/eureka/DomainExtractingServerListTests.java
  spring-cloud-netflix-eureka-client/src/test/java/org/springframework/cloud/netflix/ribbon/eureka/RibbonEurekaAutoConfigurationTests.java
  spring-cloud-netflix-eureka-server/src/main/java/org/springframework/cloud/netflix/eureka/server/EurekaController.java
  spring-cloud-netflix-eureka-server/src/main/java/org/springframework/cloud/netflix/eureka/server/EurekaServerInitializerConfiguration.java
  spring-cloud-netflix-eureka-server/src/test/java/org/springframework/cloud/netflix/eureka/server/RefreshablePeerEurekaNodesTests.java
Labels: waiting-for-triage

#3667 Gh 3464 upgrade scc new
  pom.xml
  spring-cloud-netflix-hystrix-contract/pom.xml
  spring-cloud-netflix-turbine-stream/pom.xml
  spring-cloud-netflix-turbine-stream/src/test/java/org/springframework/cloud/netflix/turbine/stream/TurbineStreamTests.java
Labels: waiting-for-triage
