Repository spring-cloud/spring-cloud-netflix, pull requests merged in 2020-01, with the labels that each got.

#3729 Fix misspelling in sagan index
  docs/src/main/asciidoc/sagan-index.adoc
Labels: documentation

#3728 fixed #3692 issue
  spring-cloud-netflix-archaius/src/main/java/org/springframework/cloud/netflix/archaius/ArchaiusAutoConfiguration.java
  spring-cloud-netflix-archaius/src/test/java/org/springframework/cloud/netflix/archaius/LazyLoadConfigurationTests.java
Labels: bug

#3687 HTTP clients - fix typos in docs
  docs/src/main/asciidoc/spring-cloud-netflix.adoc
Labels: documentation

#3693 Optimize some code
  spring-cloud-netflix-turbine-stream/src/main/java/org/springframework/cloud/netflix/turbine/stream/TurbineController.java
  spring-cloud-netflix-turbine-stream/src/test/java/org/springframework/cloud/netflix/turbine/stream/HystrixStreamAggregatorTests.java
  spring-cloud-netflix-turbine/src/main/java/org/springframework/cloud/netflix/turbine/SpringClusterMonitor.java
  spring-cloud-netflix-turbine/src/test/java/org/springframework/cloud/netflix/turbine/TurbineHttpTests.java
  spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/filters/post/LocationRewriteFilter.java
  spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/filters/post/SendResponseFilter.java
  spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/filters/route/RibbonRoutingFilter.java
  spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/filters/route/SimpleHostRoutingFilter.java
  spring-cloud-netflix-zuul/src/main/java/org/springframework/cloud/netflix/zuul/util/RequestContentDataExtractor.java
Labels: task
