Repository spring-cloud/spring-cloud-netflix, pull requests merged in 2022-03, with the labels that each got.

#4075 Upgrade Eureka Server GUI dependencies and components.
  spring-cloud-netflix-eureka-client/src/test/java/org/springframework/cloud/netflix/eureka/http/EurekaServerMockApplication.java
  spring-cloud-netflix-eureka-server/pom.xml
  spring-cloud-netflix-eureka-server/src/main/wro/header.css
  spring-cloud-netflix-eureka-server/src/main/wro/header.less
  spring-cloud-netflix-eureka-server/src/main/wro/main.css
  spring-cloud-netflix-eureka-server/src/main/wro/main.less
  spring-cloud-netflix-eureka-server/src/main/wro/responsive.css
  spring-cloud-netflix-eureka-server/src/main/wro/responsive.less
  spring-cloud-netflix-eureka-server/src/main/wro/typography.css
  spring-cloud-netflix-eureka-server/src/main/wro/typography.less
  spring-cloud-netflix-eureka-server/src/main/wro/wro.properties
  spring-cloud-netflix-eureka-server/src/main/wro/wro.xml
  src/checkstyle/checkstyle-suppressions.xml
Labels: dependencies

#4079 Documents the eureka version in the context path (#674)
  docs/src/main/asciidoc/spring-cloud-netflix.adoc
Labels: documentation

#4074 Get health from composite indicators
  spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/EurekaHealthCheckHandler.java
  spring-cloud-netflix-eureka-client/src/test/java/org/springframework/cloud/netflix/eureka/EurekaHealthCheckHandlerTests.java
Labels: bug

#4083 Documented eureka.server.defaultOpenForTrafficCount
  docs/src/main/asciidoc/spring-cloud-netflix.adoc
Labels: documentation
